#!/bin/zsh

export SPACESHIP_PACKAGE_SHOW=false
export SPACESHIP_NODE_SHOW=false
export SPACESHIP_XCODE_SHOW_GLOBAL=false
export SPACESHIP_SWIFT_SHOW_LOCAL=false
export SPACESHIP_PHP_SHOW=false
export SPACESHIP_VI_MODE_SHOW=false

export SPACESHIP_RUBY_SYMBOL='\uf43b '
export SPACESHIP_ELIXIR_SYMBOL='\ue62d '
export SPACESHIP_GOLANG_SYMBOL='\ufcd1 '
export SPACESHIP_DOCKER_SYMBOL='\ue7b0 '
